#!/bin/bash



# Pass maintainer script parameters to hook scripts
export DEB_MAINT_PARAMS="$*"

# Tell initramfs builder whether it's wanted
export INITRD=Yes

test -d /etc/kernel/postinst.d && run-parts --arg="4.17.14-sunxi" --arg="/boot/vmlinuz-4.17.14-sunxi" /etc/kernel/postinst.d

if [ "$(grep nand /proc/partitions)" != "" ] && [ "$(grep mmc /proc/partitions)" = "" ]; then
	mkimage -A arm -O linux -T kernel -C none -a "0x40008000" -e "0x40008000" -n "Linux kernel" -d /boot/vmlinuz-4.17.14-sunxi /boot/uImage  > /dev/null 2>&1
	cp /boot/uImage /tmp/uImage
	sync
	mountpoint -q /boot || mount /boot
	cp /tmp/uImage /boot/uImage
	rm -f /boot/vmlinuz-4.17.14-sunxi
else
	ln -sf vmlinuz-4.17.14-sunxi /boot/zImage || mv /boot/vmlinuz-4.17.14-sunxi /boot/zImage
fi
touch /boot/.next
exit 0
